# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CPrb2tpTrUnyuaIzoQszIj9ZsV7Je6xF
"""

import streamlit as st
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import seaborn as sns

# Load the trained model
model = pickle.load(open("churn_model.pkl", "rb"))

# Title
st.title("📊 Customer Churn Prediction Dashboard")

# Tabs
tab1, tab2 = st.tabs(["🔮 Predict Churn", "📋 Churn Distribution"])

# --- TAB 1: Predict Churn ---
with tab1:
    st.header("Predict Churn for a New Customer")

    # User Input Form
    with st.form("churn_form"):
        tenure = st.number_input("Tenure (months)", min_value=0, value=12)
        phone = st.selectbox("Phone Service (1 = Yes, 0 = No)", [1, 0])
        contract = st.selectbox("Contract Type (0 = M2M, 1 = One year, 2 = Two year)", [0, 1, 2])
        billing = st.selectbox("Paperless Billing (1 = Yes, 0 = No)", [1, 0])
        payment = st.selectbox("Payment Method (0 = E-check, 1 = Mailed, 2 = Bank, 3 = Credit Card)", [0, 1, 2, 3])
        monthly = st.number_input("Monthly Charges", value=70.0)
        total = st.number_input("Total Charges", value=500.0)

        submit = st.form_submit_button("Predict")

        if submit:
            input_df = pd.DataFrame({
                'tenure': [tenure],
                'PhoneService': [phone],
                'Contract': [contract],
                'PaperlessBilling': [billing],
                'PaymentMethod': [payment],
                'MonthlyCharges': [monthly],
                'TotalCharges': [total]
            })

            pred = model.predict(input_df)[0]
            prob = model.predict_proba(input_df)[0][1]

            if pred == 1:
                st.error(f"⚠️ This customer is likely to churn! (Confidence: {prob:.2%})")
            else:
                st.success(f"✅ This customer is likely to stay. (Confidence: {1 - prob:.2%})")

# --- TAB 2: Churn Distribution ---
with tab2:
    st.header("Churn Distribution Charts")

    try:

        df = pd.read_csv("your_dataset.csv")

        col1, col2 = st.columns(2)

        with col1:
            st.subheader("By Contract Type")
            fig1, ax1 = plt.subplots()
            sns.countplot(x='Contract', hue='Churn', data=df, ax=ax1)
            ax1.set_xlabel("Contract Type (0=M2M, 1=1yr, 2=2yr)")
            st.pyplot(fig1)

        with col2:
            st.subheader("By Payment Method")
            fig2, ax2 = plt.subplots()
            sns.countplot(x='PaymentMethod', hue='Churn', data=df, ax=ax2)
            ax2.set_xlabel("Payment Method (0=E-check, 1=Mailed, 2=Bank, 3=Card)")
            plt.xticks(rotation=45)
            st.pyplot(fig2)

    except FileNotFoundError:
        st.warning("Upload your dataset as 'your_dataset.csv' to see distribution charts.")
